// <auto-generated />
using System;
using System.Collections.Generic;

namespace Hexed;

public sealed class GeneratedDescriptor : Descriptor
{
    public IEnumerable<Type> UsedModules(Type moduleType)
    {
        if (moduleType == typeof(AppModule))
            return [typeof(OtherModule)];
        return [];
    }

    public IEnumerable<Type> GlobbedModules(Type moduleType)
    {
        return [];
    }

    public IEnumerable<Type> ConfiguredModules(Type moduleType)
    {
        return [];
    }

    public IEnumerable<Type> ConfiguredComponents(Type moduleType)
    {
        return [];
    }

    public Module CreateModule(Type moduleType)
    {
        if (moduleType == typeof(AppModule)) return new AppModule();
        if (moduleType == typeof(OtherModule)) return new OtherModule();
        throw new InvalidOperationException($"Unknown module type {moduleType}");
    }

    public void InvokeConfigure(object module, Type configurableType, object dependency)
    {
        throw new InvalidOperationException($"Unknown configure invocation {module.GetType()} / {configurableType}");
    }
}

internal static class HexedInitializer
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::Hexed.Modules.Descriptor = new GeneratedDescriptor();
    }
}
