// <auto-generated />
using System;
using System.Collections.Generic;

namespace Hexed;

public sealed class GeneratedDescriptor : Descriptor
{
    public IEnumerable<Type> UsedModules(Type moduleType)
    {
        if (moduleType == typeof(global::AppModule))
            return [typeof(global::OtherModule)];
        if (moduleType == typeof(global::GlobbingModule))
            return [typeof(global::GlobbedModule)];
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::ModuleViaConfigure)];
        return [];
    }

    public IEnumerable<Type> GlobbedModules(Type moduleType)
    {
        if (moduleType == typeof(global::GlobbingModule))
            return [typeof(global::GlobbedModule)];
        return [];
    }

    public IEnumerable<Type> ConfiguredModules(Type moduleType)
    {
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::ModuleViaConfigure)];
        return [];
    }

    public IEnumerable<Type> ConfiguredComponents(Type moduleType)
    {
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::SomeComponent)];
        return [];
    }

    public Module CreateModule(Type moduleType)
    {
        if (moduleType == typeof(global::AppModule)) return new global::AppModule();
        if (moduleType == typeof(global::OtherModule)) return new global::OtherModule();
        if (moduleType == typeof(global::GlobbingModule)) return new global::GlobbingModule();
        if (moduleType == typeof(global::GlobbedModule)) return new global::GlobbedModule();
        if (moduleType == typeof(global::ConfiguringModule)) return new global::ConfiguringModule();
        if (moduleType == typeof(global::ModuleViaConfigure)) return new global::ModuleViaConfigure();
        throw new InvalidOperationException($"Unknown module type {moduleType}");
    }

    public void InvokeConfigure(object module, Type configurableType, object dependency)
    {
        if (module is global::ConfiguringModule && configurableType == typeof(global::ModuleViaConfigure))
        { ((global::ConfiguringModule)module).Configure((global::ModuleViaConfigure)dependency); return; }
        if (module is global::ConfiguringModule && configurableType == typeof(global::SomeComponent))
        { ((global::ConfiguringModule)module).Configure((global::SomeComponent)dependency); return; }
        throw new InvalidOperationException($"Unknown configure invocation {module.GetType()} / {configurableType}");
    }
}

internal static class HexedInitializer
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::Hexed.Modules.Descriptor = new global::Hexed.GeneratedDescriptor();
    }
}
