// <auto-generated />
using System;
using System.Collections.Generic;

namespace Hexed;

public sealed class GeneratedMetadata : Metadata
{
    public IEnumerable<Type> UsedModules(Type moduleType)
    {
        if (moduleType == typeof(global::AppModule))
            return [typeof(global::OtherModule)];
        if (moduleType == typeof(global::GlobbingModule))
            return [typeof(global::GlobbedModule)];
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::ModuleViaConfigure)];
        if (moduleType == typeof(global::ModuleUsingNested))
            return [typeof(global::Container.NestedModule)];
        if (moduleType == typeof(global::AnotherModule))
            return [typeof(global::SomeGeneric<int>)];
        return [];
    }

    public IEnumerable<Type> GlobbedModules(Type moduleType)
    {
        if (moduleType == typeof(global::GlobbingModule))
            return [typeof(global::GlobbedModule)];
        return [];
    }

    public IEnumerable<Type> ConfiguredModules(Type moduleType)
    {
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::ModuleViaConfigure)];
        return [];
    }

    public IEnumerable<Type> ConfiguredComponents(Type moduleType)
    {
        if (moduleType == typeof(global::ConfiguringModule))
            return [typeof(global::SomeComponent)];
        return [];
    }

    public Module CreateModule(Type moduleType)
    {
        if (moduleType == typeof(global::AppModule)) return new global::AppModule();
        if (moduleType == typeof(global::OtherModule)) return new global::OtherModule();
        if (moduleType == typeof(global::GlobbingModule)) return new global::GlobbingModule();
        if (moduleType == typeof(global::GlobbedModule)) return new global::GlobbedModule();
        if (moduleType == typeof(global::ConfiguringModule)) return new global::ConfiguringModule();
        if (moduleType == typeof(global::ModuleViaConfigure)) return new global::ModuleViaConfigure();
        if (moduleType == typeof(global::Container.NestedModule)) return new global::Container.NestedModule();
        if (moduleType == typeof(global::ModuleUsingNested)) return new global::ModuleUsingNested();
        if (moduleType == typeof(global::AnotherModule)) return new global::AnotherModule();
        if (moduleType == typeof(global::SomeGeneric<int>)) return new global::SomeGeneric<int>();
        throw new global::Hexed.HexedException.UnknownModule($"Unknown module type {moduleType}");
    }

    public void InvokeConfigure(object module, Type configurableType, object dependency)
    {
        if (module is global::ConfiguringModule && configurableType == typeof(global::ModuleViaConfigure))
        { ((global::ConfiguringModule)module).Configure((global::ModuleViaConfigure)dependency); return; }
        if (module is global::ConfiguringModule && configurableType == typeof(global::SomeComponent))
        { ((global::ConfiguringModule)module).Configure((global::SomeComponent)dependency); return; }
        throw new global::Hexed.HexedException.UnknownConfigureInvocation($"Unknown configure invocation {module.GetType()} / {configurableType}");
    }
}

internal static class HexedInitializer
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::Hexed.Modules.Metadata = new global::Hexed.GeneratedMetadata();
    }
}
