// <auto-generated />
using System;

namespace Hexed;

internal static class HexedInitializer
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::Hexed.Modules.Metadata.Register(typeof(global::AppModule), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::OtherModule)],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::AppModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::OtherModule), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::OtherModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::GlobbingModule), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::GlobbedModule)],
            GlobbedModules = [typeof(global::GlobbedModule)],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::GlobbingModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::GlobbedModule), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::GlobbedModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::ConfiguringModule), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::ModuleViaConfigure)],
            GlobbedModules = [],
            ConfiguredModules = [typeof(global::ModuleViaConfigure)],
            ConfiguredComponents = [typeof(global::SomeComponent)],
            Factory = () => new global::ConfiguringModule(),
            Configure = (module, type, dep) =>
            {
                switch (dep)
                {
                    case global::ModuleViaConfigure typed:
                        ((global::ConfiguringModule)module).Configure(typed);
                        break;
                    case global::SomeComponent typed:
                        ((global::ConfiguringModule)module).Configure(typed);
                        break;
                }
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::ModuleViaConfigure), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::ModuleViaConfigure(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::Container.NestedModule), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::Container.NestedModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::ModuleUsingNested), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::Container.NestedModule)],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::ModuleUsingNested(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::AnotherModule), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::SomeGeneric<int>)],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::AnotherModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::MyApp.NamespacedModule), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::MyApp.NamespacedModule(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::MyApp.ModuleUsingNamespace), new global::Hexed.Metadata
        {
            UsedModules = [typeof(global::MyApp.NamespacedModule)],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::MyApp.ModuleUsingNamespace(),
            Configure = (module, type, dep) =>
            {
            }
        });

        global::Hexed.Modules.Metadata.Register(typeof(global::SomeGeneric<int>), new global::Hexed.Metadata
        {
            UsedModules = [],
            GlobbedModules = [],
            ConfiguredModules = [],
            ConfiguredComponents = [],
            Factory = () => new global::SomeGeneric<int>(),
            Configure = (module, type, dep) =>
            {
            }
        });

    }
}
