using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Hexed.Analyzer;

[Generator]
public sealed class MetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var moduleTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetModuleType(ctx, ct))
            .Where(static t => t is not null);

        var compilationAndModules = moduleTypes.Collect()
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(
            compilationAndModules,
            static (ctx, tuple) => Execute(ctx, tuple.Left, tuple.Right));
    }

    private static INamedTypeSymbol? GetModuleType(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var declaration = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(declaration, ct) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract)
            return null;

        var moduleType = ctx.SemanticModel.Compilation.GetTypeByMetadataName("Hexed.Module");

        if (moduleType is null)
            return null;

        if (IsModule(symbol, moduleType))
        {
            return symbol;
        }

        return null;
    }

    private static void Execute(SourceProductionContext ctx,
        ImmutableArray<INamedTypeSymbol?> moduleSymbols, Compilation compilation)
    {
        var entryModules = moduleSymbols
            .Where(m => m is not null)
            .Select(m => m!)
            .ToList();

        if (entryModules.Count == 0)
            return;

        var moduleType = compilation.GetTypeByMetadataName("Hexed.Module");
        var useType = compilation.GetTypeByMetadataName("Hexed.Use`1");
        var globType = compilation.GetTypeByMetadataName("Hexed.Glob`1");
        var configureType = compilation.GetTypeByMetadataName("Hexed.Configure`1");

        if (moduleType is null || useType is null || globType is null || configureType is null)
            return;

        var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var localModules = new Dictionary<INamedTypeSymbol, INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var queue = new Queue<INamedTypeSymbol>(entryModules);

        while (queue.Count > 0)
        {
            var module = queue.Dequeue();

            if (!visited.Add(module))
                continue;

            if (SymbolEqualityComparer.Default.Equals(module.ContainingAssembly, compilation.Assembly) ||
                (module.IsGenericType && !module.IsDefinition))
            {
                localModules[module] = module;
            }

            foreach (var iface in module.AllInterfaces)
            {
                if (!iface.IsGenericType)
                    continue;

                var definition = iface.OriginalDefinition;

                if (!SymbolEqualityComparer.Default.Equals(definition, useType) &&
                    !SymbolEqualityComparer.Default.Equals(definition, globType) &&
                    !SymbolEqualityComparer.Default.Equals(definition, configureType))
                    continue;

                var argument = iface.TypeArguments[0] as INamedTypeSymbol;

                if (argument is null)
                    continue;

                if (IsModule(argument, moduleType) && !visited.Contains(argument))
                    queue.Enqueue(argument);
            }
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace Hexed;");
        sb.AppendLine();
        sb.AppendLine("internal static class HexedInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        foreach (var module in localModules.Values)
        {
            var typeName = TypeOfString(module);
            var castType = GlobalType(module);
            var used = GetInterfaceArguments(module, useType)
                .Where(t => IsModule(t, moduleType))
                .ToList();
            var globbed = GetInterfaceArguments(module, globType)
                .Where(t => IsModule(t, moduleType))
                .ToList();
            var allConfigured = GetInterfaceArguments(module, configureType).ToList();
            var configuredModules = allConfigured.Where(t => IsModule(t, moduleType)).ToList();
            var components = allConfigured.Where(t => !IsModule(t, moduleType)).ToList();

            var isOpenGeneric = module.IsGenericType && module.IsDefinition;
            var isForeignClosedGeneric = module.IsGenericType && !module.IsDefinition
                && !SymbolEqualityComparer.Default.Equals(module.ContainingAssembly, compilation.Assembly);

            if (isForeignClosedGeneric)
            {
                used.Clear();
                globbed.Clear();
                configuredModules.Clear();
                components.Clear();
            }

            sb.AppendLine($"        global::Hexed.Modules.Metadata.Register(typeof({typeName}), new global::Hexed.Metadata");
            sb.AppendLine("        {");
            sb.AppendLine($"            UsedModules = [{string.Join(", ", used.Select(t => $"typeof({TypeOfString(t)})"))}],");
            sb.AppendLine($"            GlobbedModules = [{string.Join(", ", globbed.Select(t => $"typeof({TypeOfString(t)})"))}],");
            sb.AppendLine($"            ConfiguredModules = [{string.Join(", ", configuredModules.Select(t => $"typeof({TypeOfString(t)})"))}],");
            sb.AppendLine($"            ConfiguredComponents = [{string.Join(", ", components.Select(t => $"typeof({TypeOfString(t)})"))}],");
            if (isOpenGeneric || (!isForeignClosedGeneric && !module.Constructors.Any(c => c.Parameters.Length == 0 && !c.IsStatic)))
            {
                sb.AppendLine($"            Factory = () => throw new global::System.InvalidOperationException($\"Module {{typeof({typeName})}} must be created via Load(instance)\"),");
            }
            else
            {
                sb.AppendLine($"            Factory = () => new {castType}(),");
            }
            sb.AppendLine("            Configure = (module, dep) =>");
            sb.AppendLine("            {");

            if (!isOpenGeneric && allConfigured.Count > 0)
            {
                sb.AppendLine("                switch (dep)");
                sb.AppendLine("                {");

                foreach (var configured in allConfigured)
                {
                    var configuredType = GlobalType(configured);
                    sb.AppendLine($"                    case {configuredType} typed:");
                    sb.AppendLine($"                        (({castType})module).Configure(typed);");
                    sb.AppendLine($"                        break;");
                }

                sb.AppendLine("                }");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        });");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedMetadata.g.cs", sb.ToString());
    }

    private static bool IsModule(INamedTypeSymbol symbol, INamedTypeSymbol moduleType)
    {
        return symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, moduleType));
    }

    private static IEnumerable<INamedTypeSymbol> GetInterfaceArguments(INamedTypeSymbol symbol, INamedTypeSymbol openGenericType) =>
        symbol.AllInterfaces
            .Where(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, openGenericType))
            .Select(i => i.TypeArguments[0])
            .OfType<INamedTypeSymbol>();

    private static string GlobalType(INamedTypeSymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string TypeOfString(INamedTypeSymbol symbol)
    {
        if (symbol.IsGenericType && symbol.IsDefinition)
        {
            var baseName = symbol.ToDisplayString(new SymbolDisplayFormat(
                globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                genericsOptions: SymbolDisplayGenericsOptions.None));
            var arity = symbol.TypeParameters.Length;
            return $"{baseName}<{new string(',', arity - 1)}>";
        }
        return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }
}