using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Hexed.Analyzer;

[Generator]
public sealed class ModuleDescriptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var moduleTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetModuleType(ctx, ct))
            .Where(static t => t is not null);

        context.RegisterSourceOutput(
            moduleTypes.Collect(),
            static (ctx, modules) => Execute(ctx, modules));
    }

    private static INamedTypeSymbol? GetModuleType(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var declaration = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(declaration, ct) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract)
            return null;

        if (IsModule(symbol))
        {
            return symbol;
        }

        return null;
    }

    private static void Execute(SourceProductionContext ctx,
        ImmutableArray<INamedTypeSymbol?> moduleSymbols)
    {
        var entryModules = moduleSymbols
            .Where(m => m is not null)
            .Select(m => m!)
            .ToList();

        if (entryModules.Count == 0)
            return;

        // transitively discover all reachable module types
        var allModules = new Dictionary<string, INamedTypeSymbol>();
        var queue = new Queue<INamedTypeSymbol>(entryModules);

        while (queue.Count > 0)
        {
            var module = queue.Dequeue();
            var key = module.ToDisplayString();

            if (allModules.ContainsKey(key))
                continue;

            allModules[key] = module;

            foreach (var iface in module.AllInterfaces)
            {
                if (!iface.IsGenericType)
                    continue;

                var definition = iface.OriginalDefinition.ToDisplayString();

                if (definition is not ("Hexed.Use<TModule>" or "Hexed.Glob<TModule>" or "Hexed.Configure<TComponent>"))
                    continue;

                var argument = iface.TypeArguments[0] as INamedTypeSymbol;

                if (argument is null)
                    continue;

                if (IsModule(argument) && !allModules.ContainsKey(argument.ToDisplayString()))
                    queue.Enqueue(argument);
            }
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Hexed;");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedModuleDescriptor : ModuleDescriptor");
        sb.AppendLine("{");

        // UsedModules
        sb.AppendLine("    public IEnumerable<Type> UsedModules(Type moduleType)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            var used = GetInterfaceArguments(module, "Hexed.Use<T>")
                .Where(IsModule)
                .ToList();

            if (used.Count == 0)
                continue;

            sb.AppendLine($"        if (moduleType == typeof({module.ToDisplayString()}))");
            sb.AppendLine(
                $"            return [{string.Join(", ", used.Select(t => $"typeof({t.ToDisplayString()})"))}];");
        }

        sb.AppendLine("        return [];");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GlobbedModules
        sb.AppendLine("    public IEnumerable<Type> GlobbedModules(Type moduleType)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            var globbed = GetInterfaceArguments(module, "Hexed.Glob<TModule>")
                .Where(IsModule)
                .ToList();

            if (globbed.Count == 0)
                continue;

            sb.AppendLine($"        if (moduleType == typeof({module.ToDisplayString()}))");
            sb.AppendLine(
                $"            return [{string.Join(", ", globbed.Select(t => $"typeof({t.ToDisplayString()})"))}];");
        }

        sb.AppendLine("        return [];");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ConfiguredModules
        sb.AppendLine("    public IEnumerable<Type> ConfiguredModules(Type moduleType)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            var configured = GetInterfaceArguments(module, "Hexed.Configure<T>")
                .Where(IsModule)
                .ToList();

            if (configured.Count == 0)
                continue;

            sb.AppendLine($"        if (moduleType == typeof({module.ToDisplayString()}))");
            sb.AppendLine(
                $"            return [{string.Join(", ", configured.Select(t => $"typeof({t.ToDisplayString()})"))}];");
        }

        sb.AppendLine("        return [];");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ConfiguredComponents
        sb.AppendLine("    public IEnumerable<Type> ConfiguredComponents(Type moduleType)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            var components = GetInterfaceArguments(module, "Hexed.Configure<T>")
                .Where(t => !IsModule(t))
                .ToList();

            if (components.Count == 0)
                continue;

            sb.AppendLine($"        if (moduleType == typeof({module.ToDisplayString()}))");
            sb.AppendLine(
                $"            return [{string.Join(", ", components.Select(t => $"typeof({t.ToDisplayString()})"))}];");
        }

        sb.AppendLine("        return [];");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CreateModule
        sb.AppendLine("    public Module CreateModule(Type moduleType)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            sb.AppendLine(
                $"        if (moduleType == typeof({module.ToDisplayString()})) return new {module.ToDisplayString()}();");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unknown module type {moduleType}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        // InvokeConfigure
        sb.AppendLine("    public void InvokeConfigure(object module, Type configurableType, object dependency)");
        sb.AppendLine("    {");
        foreach (var module in allModules.Values)
        {
            var allConfigured = GetInterfaceArguments(module, "Hexed.Configure<T>").ToList();

            foreach (var configured in allConfigured)
            {
                sb.AppendLine(
                    $"        if (module is {module.ToDisplayString()} m_{Sanitize(module)} && configurableType == typeof({configured.ToDisplayString()}))");
                sb.AppendLine(
                    $"        {{ (({module.ToDisplayString()})m_{Sanitize(module)}).Configure(({configured.ToDisplayString()})dependency); return; }}");
            }
        }

        sb.AppendLine(
            "        throw new InvalidOperationException($\"Unknown configure invocation {module.GetType()} / {configurableType}\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static class HexedInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::Hexed.Modules.Descriptor = new GeneratedModuleDescriptor();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedModuleDescriptor.g.cs", sb.ToString());
    }

    private static bool IsModule(INamedTypeSymbol symbol)
    {
        return symbol.AllInterfaces.Any(i => i.ToDisplayString() == "Hexed.Module");
    }

    private static IEnumerable<INamedTypeSymbol> GetInterfaceArguments(INamedTypeSymbol symbol, string openGeneric) =>
        symbol.AllInterfaces
            .Where(i => i.IsGenericType && i.OriginalDefinition.ToDisplayString() == openGeneric)
            .Select(i => i.TypeArguments[0])
            .OfType<INamedTypeSymbol>();

    private static string Sanitize(INamedTypeSymbol symbol) =>
        symbol.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_");
}